#!/bin/bash
#SBATCH -N 1 
#SBATCH -p GPU-shared
#SBATCH --gpus=v100-32:1        # or gpu:h100-80:1 or gpu:l40s-48:1
#SBATCH -t 08:00:00

#SBATCH --output=myjob.%j.out
#SBATCH --error=myjob.%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ghanem.p@northeastern.edu

# -----------------------------
# Load conda (Bridges-2 way)
# -----------------------------
module load anaconda3/2024.10-1
conda activate rirl

# (Optional) Load CUDA toolkit only if your code uses nvcc or custom kernels
# module load cuda/12.3

echo "Running on node: $SLURM_NODELIST"
echo "CUDA_VISIBLE_DEVICES = $CUDA_VISIBLE_DEVICES"

# -----------------------------
# Run your RIRL experiment
# -----------------------------
python main.py \
    --seed=$SEED \
    --horizon=50 \
    --N_steps=1000 \
    --N_steps_expert=1000 \
    --gym_env="CartPole-v1" \
    --lr=1e-4 \
    --num_traj=2000\
    --reward_fn_updates=15 \
    --lambda_=0.001 \
    --rirl_iterations=1000 \
    --Q=1e-4 \
    --P=1e-1 \
    --hidden_dim=16

